GET http://localhost:5000/seats/
Content-Type: application/json
###
GET https://leadratbackend.onrender.com/seats/
Content-Type: application/json
###
POST https://leadratbackend.onrender.com/book/
Content-Type: application/json

[
    {
        "row": "A",
        "id": 2
    }
]
