GET http://localhost:5000/seats/
Content-Type: application/json
###
POST http://localhost:5000/book/
Content-Type: application/json

[
    {
        "row": "A",
        "id": 2
    },
    {
        "row": "A",
        "id": 3
    },
    {
        "row": "A",
        "id": 4
    }
]
